In [1]:
import sys
sys.path.insert(0, '..')

In [2]:
%matplotlib inline
import matplotlib
from scipy.io import loadmat
from os.path import basename
import numpy as np
from scipy import ndimage
import matplotlib.pyplot as plt
from pymr.heart import ahaseg

In [3]:
import nibabel
heart = nibabel.load(r"test_gt.nii.gz").get_fdata()

In [4]:
import pymr.heart as pyheart

In [5]:
for ii in range(heart.shape[2]):
    result = pyheart.thickness.thick_ana_xyt(heart[..., ii, :])

-1
-1
-1
-1
[0.06875    0.09368687 0.02634249 0.11638418 0.2245269  0.11807801]
[0.07782039 0.14860849 0.01165839 0.05555556 0.10872317 0.11778042]
[0.05853051 0.10772579 0.08162738 0.06071239 0.02564103 0.12169312]
[ 0.17432362  0.09722488  0.00532189 -0.03323864 -0.18966292 -0.03055385]
[ 0.04096746  0.17369727  0.11789277 -0.12763476 -0.25938108  0.11454545]
[0.01568244 0.27579737 0.11650615 0.08563669 0.23781979 0.07697181]
[0.12470242 0.15364696 0.10617177 0.14459584 0.17364841 0.24208725]
-1
-1


In [ ]:
pyheart.thickness.get_frame(heart)

In [ ]:
heart_crop, crop = pyheart.auto_crop(heart)
motion_map_list = []
for ii in range(heart_crop.shape[2]):
    print(ii)
    heart_mask = heart_crop[..., ii, :]
    motion_vector, motion_map = pyheart.motion.motion_ana_xyt(heart_mask, nseg=6, display=True)
    if np.sum(motion_map)==0:
        continue
    motion_map_list.append(motion_map)

plt.figure(figsize=(30,5))
plt.imshow(np.hstack(motion_map_list))
plt.axis('off')
